allure

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,5 +1,7 @@
 
 
+
+
 name: Test and Deploy Service
 
 on:
@@ -26,16 +28,12 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-          pip install -r requirements.txt
-          pip install allure-pytest
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
       #  Running tests with coverage and generating XML report
       - name: Run tests with coverage
         run: |
-          mkdir -p allure-results
-          pytest --cov --cov-branch --cov-report=xml --alluredir=allure-results tests/
-
+          pytest --cov --cov-branch --cov-report=xml
 
       #  Uploading coverage  report to Codecov
       - name: Upload coverage to Codecov
@@ -44,55 +42,6 @@ jobs:
           file: ./coverage.xml
           token: ${{ secrets.CODECOV_TOKEN }}
           fail_ci_if_error: true
-
-      - name: Upload Allure results as artifact
-        uses: actions/upload-artifact@v4
-        if: always()  # Upload even if tests fail
-        with:
-          name: allure-results
-          path: allure-results/
-          retention-days: 30
-
-  allure-report:
-    runs-on: ubuntu-latest
-    needs: test
-    if: always()
-    
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        
-      - name: Download all Allure results
-        uses: actions/download-artifact@v4
-        with:
-          pattern: allure-results-*
-          path: allure-results-downloaded
-          merge-multiple: false
-
-
-      - name: Merge all results into single directory
-        run: |
-          mkdir -p allure-results
-          for dir in allure-results-downloaded/*/; do
-            if [ -d "$dir" ]; then
-              cp -r "$dir"* allure-results/ 2>/dev/null || true
-            fi
-          done
-          
-      - name: Generate and Deploy Allure Report
-        uses: simple-elf/allure-report-action@master
-        with:
-          allure_results: allure-results
-          allure_report: allure-report
-          gh_pages: gh-pages
-          allure_history: allure-history
-          keep_reports: 20
-   
-      - name: Deploy to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}
-          publish_dir: allure-history
 
   deploy:
     runs-on: ubuntu-latest
@@ -127,6 +76,151 @@ jobs:
 
             sudo systemctl daemon-reload
             sudo systemctl restart yolo || sudo systemctl start yolo
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+# name: Test and Deploy Service
+
+# on:
+#   push:
+#     branches:
+#       - main
+#   workflow_dispatch:
+
+# jobs:
+#   test:
+#     runs-on: ubuntu-latest
+#     steps:
+#       # Step One: Download the Code
+#       - name: Checkout code
+#         uses: actions/checkout@v4
+
+#       # Installing Python version
+#       - name: Set up Python
+#         uses: actions/setup-python@v4
+#         with:
+#           python-version: '3.10'
+
+#       # Installing dependencies (including pytest from requirements.txt)
+#       - name: Install dependencies
+#         run: |
+#           python -m pip install --upgrade pip
+#           # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+#           pip install -r requirements.txt
+#           pip install allure-pytest
+
+#       #  Running tests with coverage and generating XML report
+#       - name: Run tests with coverage
+#         run: |
+#           mkdir -p allure-results
+#           pytest --cov --cov-branch --cov-report=xml --alluredir=allure-results tests/
+
+
+#       #  Uploading coverage  report to Codecov
+#       - name: Upload coverage to Codecov
+#         uses: codecov/codecov-action@v3
+#         with:
+#           file: ./coverage.xml
+#           token: ${{ secrets.CODECOV_TOKEN }}
+#           fail_ci_if_error: true
+
+#       - name: Upload Allure results as artifact
+#         uses: actions/upload-artifact@v4
+#         if: always()  # Upload even if tests fail
+#         with:
+#           name: allure-results
+#           path: allure-results/
+#           retention-days: 30
+
+#   allure-report:
+#     runs-on: ubuntu-latest
+#     needs: test
+#     if: always()
+    
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v4
+        
+#       - name: Download all Allure results
+#         uses: actions/download-artifact@v4
+#         with:
+#           pattern: allure-results-*
+#           path: allure-results-downloaded
+#           merge-multiple: false
+
+
+#       - name: Merge all results into single directory
+#         run: |
+#           mkdir -p allure-results
+#           for dir in allure-results-downloaded/*/; do
+#             if [ -d "$dir" ]; then
+#               cp -r "$dir"* allure-results/ 2>/dev/null || true
+#             fi
+#           done
+          
+#       - name: Generate and Deploy Allure Report
+#         uses: simple-elf/allure-report-action@master
+#         with:
+#           allure_results: allure-results
+#           allure_report: allure-report
+#           gh_pages: gh-pages
+#           allure_history: allure-history
+#           keep_reports: 20
+   
+#       - name: Deploy to GitHub Pages
+#         uses: peaceiris/actions-gh-pages@v3
+#         with:
+#           github_token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}
+#           publish_dir: allure-history
+
+#   deploy:
+#     runs-on: ubuntu-latest
+#     needs: test   # deploy will only run if the tests pass
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v4
+
+#       - name: Deploy to server
+#         uses: appleboy/ssh-action@v1.0.3
+#         with:
+#           host: ${{ secrets.HOST }}
+#           username: ubuntu
+#           key: ${{ secrets.SSH_KEY }}
+#           script: |
+#             cd /home/ubuntu/YoloService || (git clone https://github.com/tmeraslan/YoloService.git && cd YoloService)
+
+#             git reset --hard
+#             git pull origin main
+
+#             if [ ! -d "venv" ]; then
+#                 sudo apt-get update
+#                 sudo apt-get install -y python3-venv python3-pip
+#                 python3 -m venv venv
+#             fi
+
+#             source venv/bin/activate
+#             pip install --upgrade pip
+#             if [ -f requirements.txt ]; then
+#                 pip install -r requirements.txt
+#             fi
+
+#             sudo systemctl daemon-reload
+#             sudo systemctl restart yolo || sudo systemctl start yolo
 
 
 
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -5,6 +5,12 @@ on:
     branches: 
       - main
 
+# Add permissions for Pages deployment
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -24,11 +30,13 @@ jobs:
         pip install -r requirements.txt
         # Install pytest and coverage tools in case they're not in requirements.txt
         pip install pytest pytest-cov
+        pip install allure-pytest
 
     #  Run tests with coverage report
     - name: Run tests with coverage
       run: |
-        pytest --cov=app --cov-report=xml --cov-report=term-missing
+        mkdir -p allure-results
+        pytest --cov=app --cov-report=xml --cov-report=term-missing   --alluredir=allure-results tests/
 
     #  Upload coverage report to Codecov
     - name: Upload coverage to Codecov
@@ -37,4 +45,53 @@ jobs:
         token: ${{ secrets.CODECOV_TOKEN }}   
         file: ./coverage.xml
         fail_ci_if_error: true
+    - name: Upload Allure results as artifact
+      uses: actions/upload-artifact@v4
+      if: always()  # Upload even if tests fail
+      with:
+          name: allure-results
+          path: allure-results/
+          retention-days: 30
+
+  allure-report:
+    runs-on: ubuntu-latest
+    needs: test
+    if: always()
+    
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        
+      - name: Download all Allure results
+        uses: actions/download-artifact@v4
+        with:
+          pattern: allure-results-*
+          path: allure-results-downloaded
+          merge-multiple: false
+
+
+      - name: Merge all results into single directory
+        run: |
+          mkdir -p allure-results
+          for dir in allure-results-downloaded/*/; do
+            if [ -d "$dir" ]; then
+              cp -r "$dir"* allure-results/ 2>/dev/null || true
+            fi
+          done
+          
+      - name: Generate and Deploy Allure Report
+        uses: simple-elf/allure-report-action@master
+        with:
+          allure_results: allure-results
+          allure_report: allure-report
+          gh_pages: gh-pages
+          allure_history: allure-history
+          keep_reports: 20
+   
+      - name: Deploy to GitHub Pages
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}
+          publish_dir: allure-history
+  
  
